# Use postgres/example user/password credentials
version: "3.5"

services:
  postgres:
    container_name: postgres_container
    image: postgres:13.2
    restart: always
    environment:
      POSTGRES_DB: ecobeko
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: super_secret
    ports:
      - 5432:5432
    volumes:
      - postgres:/data/postgres

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: super_secret
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - 5480:80
    networks:
      - postgres
    volumes:
      - pgadmin:/root/.pgadmin

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:
